// SPDX-License-Identifier: Apache-2.0
import Foundation

/// The paint bucket's flood fill (#325), ported line for line from the desktop's
/// `photoslop.npimage.flood_fill`.
///
/// The desktop fill is an iterative scanline algorithm: a seed span is grown
/// left and right until it meets a pixel that is out of tolerance or already
/// filled, the span is marked, and the runs of fillable pixels directly above
/// and below it are queued by their first pixel. That is 4-connectivity — a
/// region never crosses a diagonal — and it is what makes a 1-px outline hold.
///
/// Everything here works on `PixelBuffer.words`: little-endian ARGB32
/// premultiplied, the same word the desktop's `view_u32` reads, so the
/// tolerance comparison is on premultiplied channels exactly as it is there.
/// `ipados/PhotoslopTests/Fixtures/FloodFillFixture.swift` is generated by the
/// desktop implementation and is the proof that the two agree.
enum FloodFill {
  /// Mirror of `_tolerance_mask`: within tolerance means every one of the four
  /// premultiplied channels differs from the seed by at most `tolerance`;
  /// tolerance 0 is exact word equality.
  static func withinTolerance(_ word: UInt32, of target: UInt32, tolerance: Int) -> Bool {
    if tolerance <= 0 { return word == target }
    let db = abs(Int(word & 0xFF) - Int(target & 0xFF))
    let dg = abs(Int((word >> 8) & 0xFF) - Int((target >> 8) & 0xFF))
    let dr = abs(Int((word >> 16) & 0xFF) - Int((target >> 16) & 0xFF))
    let da = abs(Int(word >> 24) - Int(target >> 24))
    return max(max(db, dg), max(dr, da)) <= tolerance
  }

  /// Mirror of `flood_mask`: the region connected to (x, y) whose pixels are
  /// within tolerance of the seed. Returns one flag per pixel (row-major) and
  /// the bounding rectangle of the region, or nil when the seed is outside the
  /// buffer.
  ///
  /// Nothing here allocates per pixel: the two masks are the only allocations,
  /// as on the desktop, and the queue holds one entry per discovered run.
  static func mask(
    words: UnsafeBufferPointer<UInt32>, width: Int, height: Int,
    x: Int, y: Int, tolerance: Int
  ) -> (mask: [Bool], bounds: PixelRect)? {
    guard x >= 0, x < width, y >= 0, y < height else { return nil }
    let seed = words[y * width + x]
    var fillable = [Bool](repeating: false, count: width * height)
    for i in 0..<(width * height) {
      fillable[i] = withinTolerance(words[i], of: seed, tolerance: tolerance)
    }
    // The seed always matches itself; the desktop check exists for the
    // selection intersection, which lands with #326.
    guard fillable[y * width + x] else { return nil }

    var filled = [Bool](repeating: false, count: width * height)
    var queue: [(Int, Int)] = [(x, y)]
    var head = 0
    var minX = x, maxX = x, minY = y, maxY = y

    while head < queue.count {
      let (sx, sy) = queue[head]
      head += 1
      let row = sy * width
      if filled[row + sx] || !fillable[row + sx] { continue }

      // Expand the span: a pixel blocks when it is out of tolerance or
      // already filled, exactly the desktop's `blocked` row.
      var left = sx
      while left > 0, fillable[row + left - 1], !filled[row + left - 1] { left -= 1 }
      var right = sx
      while right < width - 1, fillable[row + right + 1], !filled[row + right + 1] { right += 1 }

      for i in left...right { filled[row + i] = true }
      minX = min(minX, left)
      maxX = max(maxX, right)
      minY = min(minY, sy)
      maxY = max(maxY, sy)

      // Queue the first pixel of every fillable, unfilled run above and below
      // the span; the span expansion rediscovers the rest of each run.
      for ny in [sy - 1, sy + 1] where ny >= 0 && ny < height {
        let nrow = ny * width
        var inRun = false
        for i in left...right {
          let open = fillable[nrow + i] && !filled[nrow + i]
          if open && !inRun { queue.append((i, ny)) }
          inRun = open
        }
      }
    }

    // The queue only ever grows on the desktop too; drop it before the masks
    // outlive this frame.
    queue.removeAll()
    return (filled, PixelRect(x: minX, y: minY, width: maxX - minX + 1, height: maxY - minY + 1))
  }

  /// Mirror of `flood_fill`: fill the region connected to (x, y) whose pixels
  /// are within tolerance of the seed with `color` (a premultiplied ARGB32
  /// word). Returns the dirty rectangle, or nil when nothing changed — the seed
  /// is outside the buffer, or already holds the fill colour.
  @discardableResult
  static func fill(_ buffer: inout PixelBuffer, x: Int, y: Int, color: UInt32, tolerance: Int)
    -> PixelRect?
  {
    let width = buffer.width, height = buffer.height
    guard x >= 0, x < width, y >= 0, y < height else { return nil }
    if buffer.word(x: x, y: y) == color { return nil }
    guard let (mask, bounds) = buffer.withWords({ words in
      FloodFill.mask(words: words, width: width, height: height, x: x, y: y, tolerance: tolerance)
    }) else { return nil }
    buffer.withMutableWords { words in
      for i in 0..<(width * height) where mask[i] { words[i] = color }
    }
    return bounds
  }
}

/// An integer rectangle in buffer pixels, the `QRect` the desktop fill returns.
struct PixelRect: Equatable {
  var x: Int
  var y: Int
  var width: Int
  var height: Int
}
