// SPDX-License-Identifier: Apache-2.0
import UIKit
import XCTest

@testable import PhotoslopIPad

/// The appearance renderer is a port of `photoslop.appearance.render`, and the
/// effect model a port of its `new_effect`/`normalize_effect` (#316). Both are
/// held to the desktop's own output: `AppearanceFixture` is generated by
/// `scripts/gen-appearance-fixture.py` from the desktop code, and every value
/// here is compared exactly. Nothing below is allowed a tolerance: the blur is
/// the same float32 cumulative sums in the same order, so a difference would
/// mean the port has drifted, not that floating point is fickle.
final class AppearanceParityTests: XCTestCase {
  private var sourceAlpha: AlphaPlane {
    AlphaPlane(
      width: AppearanceFixture.width, height: AppearanceFixture.height,
      values: AppearanceFixture.alpha)
  }

  private func effect(_ scenario: AppearanceFixture.Scenario) throws -> LayerEffect {
    try JSONDecoder().decode(LayerEffect.self, from: Data(scenario.effect.utf8))
  }

  private func scenario(_ name: String) throws -> AppearanceFixture.Scenario {
    try XCTUnwrap(AppearanceFixture.scenarios.first { $0.name == name })
  }

  // MARK: Blur

  func testBoxBlurMatchesDesktopBitForBit() {
    let blurred = AppearanceRenderer.blur(sourceAlpha, radius: AppearanceFixture.blurRadius)
    XCTAssertEqual(blurred.width, AppearanceFixture.width)
    XCTAssertEqual(blurred.height, AppearanceFixture.height)
    XCTAssertEqual(blurred.values.count, AppearanceFixture.blurred.count)
    for (index, (ours, theirs)) in zip(blurred.values, AppearanceFixture.blurred).enumerated()
    where ours.bitPattern != theirs.bitPattern {
      XCTFail(
        "blur differs at \(index % AppearanceFixture.width),\(index / AppearanceFixture.width): "
          + "iOS \(ours) vs desktop \(theirs)")
      return
    }
  }

  func testZeroRadiusBlurIsACopy() {
    XCTAssertEqual(AppearanceRenderer.blur(sourceAlpha, radius: 0), sourceAlpha)
    XCTAssertEqual(AppearanceRenderer.blur(sourceAlpha, radius: -3), sourceAlpha)
  }

  // MARK: Every effect kind

  func testEveryFixtureScenarioRendersTheDesktopPlanes() throws {
    XCTAssertEqual(AppearanceFixture.scenarios.count, 14, "the fixture lost a scenario")
    for scenario in AppearanceFixture.scenarios {
      let planes = AppearanceRenderer.render(
        alpha: sourceAlpha, effects: [try effect(scenario)])
      XCTAssertEqual(
        planes.count, scenario.planes.count, "\(scenario.name): plane count")
      for (index, (ours, theirs)) in zip(planes, scenario.planes).enumerated() {
        let label = "\(scenario.name) plane \(index)"
        XCTAssertEqual(ours.offsetX, theirs.offsetX, "\(label): offsetX")
        XCTAssertEqual(ours.offsetY, theirs.offsetY, "\(label): offsetY")
        XCTAssertEqual(ours.under, theirs.under, "\(label): under")
        XCTAssertEqual(ours.blendMode, theirs.blendMode, "\(label): blend mode")
        XCTAssertEqual(ours.opacity, theirs.opacity, "\(label): opacity")
        XCTAssertEqual(ours.buffer.width, theirs.width, "\(label): width")
        XCTAssertEqual(ours.buffer.height, theirs.height, "\(label): height")
        guard ours.buffer.words.count == theirs.words.count else {
          XCTFail("\(label): word count \(ours.buffer.words.count) vs \(theirs.words.count)")
          continue
        }
        if let first = zip(ours.buffer.words, theirs.words).enumerated().first(where: {
          $0.element.0 != $0.element.1
        }) {
          XCTFail(
            "\(label): word \(first.offset % theirs.width),\(first.offset / theirs.width) is "
              + String(format: "0x%08X, desktop 0x%08X", first.element.0, first.element.1))
        }
      }
    }
  }

  func testDropShadowSitsUnderAndBevelSitsOver() throws {
    let shadow = AppearanceRenderer.render(
      alpha: sourceAlpha, effects: [try effect(try scenario("dropShadow"))])
    XCTAssertEqual(shadow.map(\.under), [true])
    let bevel = AppearanceRenderer.render(
      alpha: sourceAlpha, effects: [try effect(try scenario("bevelEmboss"))])
    XCTAssertEqual(bevel.map(\.under), [false, false])
    XCTAssertEqual(bevel.map(\.blendMode), ["screen", "multiply"])
  }

  func testDisabledAndUnrenderableEffectsProduceNoPlane() throws {
    XCTAssertTrue(
      AppearanceRenderer.render(alpha: sourceAlpha, effects: [try effect(try scenario("disabled"))])
        .isEmpty)
    let blur = try XCTUnwrap(LayerEffect(kind: "gaussian-blur"))
    XCTAssertTrue(AppearanceRenderer.render(alpha: sourceAlpha, effects: [blur]).isEmpty)
    XCTAssertFalse(LayerEffect.renderableKinds.contains("gaussian-blur"))
    XCTAssertFalse(LayerEffect.renderableKinds.contains("feather"))
  }

  func testStackRendersInOrderWithOneMarginForAll() throws {
    let shadow = try effect(try scenario("dropShadow"))
    let glow = try effect(try scenario("outerGlow"))
    let planes = AppearanceRenderer.render(alpha: sourceAlpha, effects: [shadow, glow])
    XCTAssertEqual(planes.count, 2)
    // Each effect pads by its own reach, as the desktop does: the shadow by
    // blur + spread = 5, then shifted by its offset; the glow by size + spread.
    XCTAssertEqual(planes.map { [$0.offsetX, $0.offsetY] }, [[-3, -2], [-4, -4]])
    XCTAssertEqual(planes.map(\.under), [true, true])
    XCTAssertEqual(AppearanceRenderer.margin(of: [shadow, glow]), 8)
    XCTAssertEqual(AppearanceRenderer.margin(of: [glow]), 4)
    XCTAssertEqual(AppearanceRenderer.margin(of: []), 0)
  }

  func testPyRoundIsBankers() {
    XCTAssertEqual(AppearanceRenderer.pyRound(0.5), 0)
    XCTAssertEqual(AppearanceRenderer.pyRound(1.5), 2)
    XCTAssertEqual(AppearanceRenderer.pyRound(2.5), 2)
    XCTAssertEqual(AppearanceRenderer.pyRound(-0.5), 0)
    XCTAssertEqual(AppearanceRenderer.pyRound(-1.5), -2)
  }

  // MARK: The source plane

  func testSourcePlaneCropsToTheOpaqueBoxPlusReach() throws {
    let format = UIGraphicsImageRendererFormat()
    format.scale = 1
    format.opaque = false
    let image = UIGraphicsImageRenderer(size: CGSize(width: 100, height: 80), format: format)
      .image { context in
        UIColor.black.setFill()
        context.fill(CGRect(x: 40, y: 30, width: 10, height: 5))
      }
    let shadow = try XCTUnwrap(
      LayerEffect(
        kind: "drop-shadow",
        parameters: ["blur": 0, "spread": 0, "offset_x": 2, "offset_y": 2]))
    // margin = 2 + 0 + 0 = 2, reach = 4 each side
    let source = try XCTUnwrap(AppearanceRenderer.sourcePlane(of: image, effects: [shadow]))
    XCTAssertEqual(source.originX, 36)
    XCTAssertEqual(source.originY, 26)
    XCTAssertEqual(source.plane.width, 18)
    XCTAssertEqual(source.plane.height, 13)
    XCTAssertEqual(source.plane[4, 4], 255)
    XCTAssertEqual(source.plane[0, 0], 0)

    let empty = UIGraphicsImageRenderer(size: CGSize(width: 10, height: 10), format: format)
      .image { _ in }
    XCTAssertNil(AppearanceRenderer.sourcePlane(of: empty, effects: [shadow]))
  }

  // MARK: The model

  func testFixtureEffectsDecodeNormalisedAndReEncodeIdentically() throws {
    for scenario in AppearanceFixture.scenarios {
      let decoded = try effect(scenario)
      XCTAssertEqual(decoded, decoded.normalized(), "\(scenario.name): already normalised")
      // The desktop wrote `4.0` where Swift writes `4`; JSON reads them alike,
      // so the comparison is of parsed objects rather than of bytes.
      let ours = try JSONDecoder().decode(
        JSONValue.self, from: try JSONEncoder().encode(decoded))
      let theirs = try JSONDecoder().decode(JSONValue.self, from: Data(scenario.effect.utf8))
      XCTAssertEqual(ours, theirs, "\(scenario.name): re-encoded shape")
    }
  }

  func testNewEffectTakesTheDesktopDefaults() throws {
    let shadow = try XCTUnwrap(LayerEffect(kind: "drop-shadow"))
    let fixture = try effect(try scenario("dropShadowDefaults"))
    XCTAssertEqual(shadow.parameters, fixture.parameters)
    XCTAssertEqual(shadow.blendMode, "normal")
    XCTAssertEqual(shadow.opacity, 1)
    XCTAssertTrue(shadow.enabled)
    XCTAssertEqual(shadow.schemaVersion, 1)
    XCTAssertEqual(shadow.id.count, 32)
    XCTAssertNil(shadow.extensions)
    XCTAssertEqual(Set(LayerEffect.defaults.keys), Set(LayerEffect.labels.keys))
    XCTAssertEqual(LayerEffect.defaults.count, 10)
    XCTAssertNil(LayerEffect(kind: "lens-flare"))
  }

  func testNormalisationClampsAndCoercesLikeTheDesktop() throws {
    let effect = try XCTUnwrap(
      LayerEffect(
        kind: "drop-shadow",
        parameters: [
          "offset_x": 99_999, "offset_y": -99_999, "blur": -4, "spread": "nope",
          "color": .array([300, -5, "12", 0.9]),
        ]))
    XCTAssertEqual(effect.number("offset_x"), 10_000)
    XCTAssertEqual(effect.number("offset_y"), -10_000)
    XCTAssertEqual(effect.number("blur"), 0)
    XCTAssertEqual(effect.number("spread"), 0, "an unreadable number takes the default")
    XCTAssertEqual(effect.rgba("color"), [255, 0, 12, 0])

    let bevel = try XCTUnwrap(
      LayerEffect(
        kind: "bevel-emboss", parameters: ["angle": 400, "depth": 0, "style": 7]))
    XCTAssertEqual(bevel.number("angle"), 360)
    XCTAssertEqual(bevel.number("depth"), 1)
    XCTAssertEqual(bevel.string("style"), "7")

    let gradient = try XCTUnwrap(
      LayerEffect(
        kind: "gradient-overlay", parameters: ["reverse": 1, "scale": 5_000, "color1": .array([1, 2, 3])]))
    XCTAssertTrue(gradient.bool("reverse"))
    XCTAssertEqual(gradient.number("scale"), 1_000)
    XCTAssertEqual(gradient.rgba("color1"), [1, 2, 3, 255], "three channels gain full alpha")

    var loose = try XCTUnwrap(LayerEffect(kind: "outer-glow"))
    loose.blendMode = "plasma"
    loose.opacity = 7
    let fixed = loose.normalized()
    XCTAssertEqual(fixed.blendMode, "normal")
    XCTAssertEqual(fixed.opacity, 1)
  }

  func testUnknownKeysSurviveAsExtensionsAndUnknownKindsAreDropped() throws {
    let json = """
      [
        {"type": "drop-shadow", "future_key": {"nested": [1, 2]}, "parameters": {"blur": 2}},
        {"type": "lens-flare", "parameters": {}},
        "not an effect",
        {"type": "outline", "blend_mode": "screen", "opacity": 0.25}
      ]
      """
    let values = try JSONDecoder().decode([JSONValue].self, from: Data(json.utf8))
    let effects = LayerEffect.normalized(values)
    XCTAssertEqual(effects.map(\.kind), ["drop-shadow", "outline"])
    XCTAssertEqual(effects[0].extensions?["future_key"], .object(["nested": .array([1, 2])]))
    XCTAssertEqual(effects[0].number("blur"), 2)
    XCTAssertEqual(effects[0].number("offset_x"), 6, "missing parameters take defaults")
    XCTAssertFalse(effects[0].id.isEmpty, "a missing id is minted")
    XCTAssertEqual(effects[1].blendMode, "screen")
    XCTAssertEqual(effects[1].opacity, 0.25)

    // The extension goes back out under `extensions`, where the desktop's
    // `normalize_effect` gathers unknown keys, and not at the top level.
    let object = try JSONDecoder().decode(
      JSONValue.self, from: try JSONEncoder().encode(effects[0]))
    guard case .object(let fields) = object else { return XCTFail("not an object") }
    XCTAssertEqual(
      fields["extensions"], .object(["future_key": .object(["nested": .array([1, 2])])]))
    XCTAssertNil(fields["future_key"])
  }

  func testPresetsMirrorTheDesktopAndMintFreshIds() throws {
    XCTAssertEqual(
      LayerEffect.presets.map(\.name),
      ["Lifted", "Sticker", "Neon", "Letterpress", "Chrome", "Soft Focus"])
    let sticker = try XCTUnwrap(LayerEffect.preset(named: "Sticker"))
    XCTAssertEqual(sticker.map(\.kind), ["drop-shadow", "outline"])
    XCTAssertEqual(sticker[1].number("width"), 6)
    XCTAssertEqual(sticker[1].rgba("color"), [255, 255, 255, 255])
    let again = try XCTUnwrap(LayerEffect.preset(named: "Sticker"))
    XCTAssertNotEqual(sticker.map(\.id), again.map(\.id))
    XCTAssertEqual(sticker.map(\.parameters), again.map(\.parameters))
    XCTAssertNil(LayerEffect.preset(named: "Nope"))
    for preset in LayerEffect.presets {
      for effect in preset.effects {
        XCTAssertEqual(effect, effect.normalized(), "\(preset.name) is stored normalised")
      }
    }
  }
}
