// SPDX-License-Identifier: Apache-2.0
import XCTest

@testable import PhotoslopIPad

/// `Dither.swift` against what `photoslop.dither` produced (#385).
///
/// `DitherFixture` is generated by `scripts/gen-dither-fixture.py` running the
/// *desktop* engine, so these are identity assertions rather than
/// re-derivations of what a dither ought to look like. They are exact and not
/// approximate on purpose: a dither turns a rounding difference into a
/// different pixel being lit, so "close" would not mean anything here.
final class DitherParityTests: XCTestCase {
  private var source: [Double] { DitherFixture.source }
  private var width: Int { DitherFixture.width }
  private var height: Int { DitherFixture.height }

  func testErrorDiffusionMatchesTheDesktop() {
    XCTAssertFalse(DitherFixture.errorDiffusion.isEmpty)
    for scenario in DitherFixture.errorDiffusion {
      let got = Dither.errorDiffuse(
        source, width: width, height: height, kernel: scenario.name, levels: scenario.levels)
      XCTAssertEqual(
        got, scenario.expected, "\(scenario.name) at \(scenario.levels) levels")
    }
  }

  func testOrderedDitherMatchesTheDesktop() {
    XCTAssertFalse(DitherFixture.ordered.isEmpty)
    for scenario in DitherFixture.ordered {
      let size = Int(scenario.name.split(separator: "-").last!)!
      let got = Dither.orderedDither(
        source, width: width, height: height, size: size, levels: scenario.levels)
      XCTAssertEqual(got, scenario.expected, "\(scenario.name) at \(scenario.levels) levels")
    }
  }

  /// The beam is compared exactly too. It is trigonometry rather than integer
  /// arithmetic, so this is the assertion most likely to be brittle across
  /// platforms — and it is worth keeping strict, because the moment it needs a
  /// tolerance the two implementations have genuinely diverged and the stipple
  /// they produce will differ pixel for pixel.
  func testBeamMaskMatchesTheDesktop() {
    XCTAssertFalse(DitherFixture.beams.isEmpty)
    for scenario in DitherFixture.beams {
      let got = Dither.beamMask(
        source, width: width, height: height, pitch: scenario.pitch,
        amplitude: scenario.amplitude)
      for index in 0..<got.count {
        XCTAssertEqual(
          got[index], scenario.expected[index], accuracy: 1e-12,
          "pitch \(scenario.pitch) amplitude \(scenario.amplitude) at \(index)")
      }
    }
  }

  func testBayerMatrixMatchesTheDesktop() {
    XCTAssertEqual(Dither.bayerMatrix(4), DitherFixture.bayer4)
  }

  /// Ties must break to even, as Python's `round` and numpy's `rint` do. A tie
  /// broken the other way is a different pixel lit, and 0.5 is exactly the
  /// value a mid-grey plane hands to a two-level quantiser.
  func testRintBreaksTiesToEven() {
    XCTAssertEqual(Dither.rint(0.5), 0)
    XCTAssertEqual(Dither.rint(1.5), 2)
    XCTAssertEqual(Dither.rint(2.5), 2)
    XCTAssertEqual(Dither.rint(-0.5), 0)
  }

  /// The property that defines error diffusion, asserted independently of the
  /// fixture: a flat mid grey rendered to pure black and white still averages
  /// to mid grey.
  func testErrorDiffusionPreservesAverageTone() {
    let flat = [Double](repeating: 0.5, count: 64 * 64)
    for kernel in Dither.errorKernels.keys.sorted() {
      let out = Dither.errorDiffuse(
        flat, width: 64, height: 64, kernel: kernel, levels: 2)
      XCTAssertTrue(out.allSatisfy { $0 == 0 || $0 == 1 }, kernel)
      let mean = out.reduce(0, +) / Double(out.count)
      XCTAssertEqual(mean, 0.5, accuracy: 0.01, kernel)
    }
  }
}
