// SPDX-License-Identifier: Apache-2.0
import UIKit
import XCTest

@testable import PhotoslopIPad

/// Gaussian Blur and Feather (#372) against pixels the desktop produced.
///
/// These are the desktop's two *fill-replacing* effects: they blur the layer's
/// premultiplied RGBA and hand back a replacement fill rather than adding a
/// plane beside it. `FillOverrideFixture` is generated by
/// `scripts/gen-fill-override-fixture.py` running the desktop's own
/// `npimage.gaussian_blur`, so every assertion here is word-for-word identity
/// with the desktop rather than a re-derivation of what it ought to do.
///
/// The fixture's radii are chosen so the blur halo spans more than one iOS
/// band. That matters: the point of banding is that the transient is bounded
/// by the radius rather than by the picture *without* changing the answer, and
/// a test whose image fits in a single band would prove nothing about it.
@MainActor
final class FillOverrideParityTests: XCTestCase {
  private func sourceBuffer() -> PixelBuffer {
    PixelBuffer(
      width: FillOverrideFixture.width, height: FillOverrideFixture.height,
      words: FillOverrideFixture.source)
  }

  func testBlurMatchesTheDesktopWordForWord() {
    for scenario in FillOverrideFixture.cases {
      let blurred = AppearanceRenderer.blurRGBA(sourceBuffer(), radius: scenario.radius)
      XCTAssertEqual(blurred.words, scenario.blurred, "gaussian blur r=\(scenario.radius)")
    }
  }

  func testFeatherMatchesTheDesktopWordForWord() {
    for scenario in FillOverrideFixture.cases {
      let feathered = AppearanceRenderer.featherRGBA(sourceBuffer(), radius: scenario.radius)
      XCTAssertEqual(feathered.words, scenario.feathered, "feather r=\(scenario.radius)")
    }
  }

  /// Feather may only eat into the silhouette, never grow it — that is the
  /// whole difference between it and a blur, and it is what lets a feathered
  /// layer stay inside its own bounds.
  func testFeatherNeverGrowsTheSilhouette() {
    let source = sourceBuffer()
    for scenario in FillOverrideFixture.cases {
      let feathered = AppearanceRenderer.featherRGBA(source, radius: scenario.radius)
      for index in 0..<source.words.count {
        let before = (source.words[index] >> 24) & 0xFF
        let after = (feathered.words[index] >> 24) & 0xFF
        XCTAssertLessThanOrEqual(after, before, "alpha grew at \(index)")
      }
    }
  }

  /// The banding claim, stated as a test.
  ///
  /// A picture whose rows are all identical must blur to a picture whose rows
  /// are all identical, away from the top and bottom edges where the window is
  /// truncated. A band seam is exactly a row that disagrees with its
  /// neighbours, so this fails loudly if a boundary ever leaks — and the image
  /// is deliberately several bands tall so there are boundaries to leak.
  ///
  /// (Total alpha is *not* conserved and must not be asserted: the window is
  /// truncated at the edges with zero outside while the divisor stays the full
  /// window, so a blur legitimately darkens towards the border. That is the
  /// desktop's behaviour, which the fixture above already pins.)
  func testBandBoundariesDoNotChangeTheResult() {
    let width = 8
    let height = PixelBuffer.bandRows * 3 + 5
    var words = [UInt32](repeating: 0, count: width * height)
    for y in 0..<height {
      for x in 0..<width {
        words[y * width + x] = x % 2 == 0 ? 0xFF00_A0FF : 0x8020_3040
      }
    }
    let radius = 9
    let blurred = AppearanceRenderer.blurRGBA(
      PixelBuffer(width: width, height: height, words: words), radius: radius)

    let margin = 3 * (radius / 2 + 1) + 1
    let reference = Array(blurred.words[margin * width..<(margin + 1) * width])
    XCTAssertNotEqual(reference, Array(words[0..<width]), "the blur did nothing")
    for y in margin..<(height - margin) {
      let row = Array(blurred.words[y * width..<(y + 1) * width])
      XCTAssertEqual(row, reference, "row \(y) disagrees with its neighbours — a band seam")
    }
  }
}
