// SPDX-License-Identifier: Apache-2.0
import UIKit
import XCTest

@testable import PhotoslopIPad

/// The paint bucket (#325) against pixels the desktop produced.
///
/// `FloodFillFixture` is generated by `scripts/gen-flood-fill-fixture.py`
/// running `photoslop.npimage.flood_fill` over the same synthetic canvas, so
/// every assertion here is word-for-word identity with the desktop, not a
/// re-derivation of what the desktop ought to do.
@MainActor
final class FloodFillParityTests: XCTestCase {
  private func fixtureBuffer() -> PixelBuffer {
    PixelBuffer(
      width: FloodFillFixture.width, height: FloodFillFixture.height,
      words: FloodFillFixture.input)
  }

  /// A fixture mask (`#` selected, `.` not) as the flags the Swift side takes.
  private func bits(_ rows: [String]) -> [Bool] {
    rows.flatMap { $0.map { $0 == "#" } }
  }

  /// Every fixture scenario: tolerance 0 outside the box, a mid tolerance
  /// inside it that crosses one band and not the next, a wide tolerance that
  /// takes the whole interior without leaking through the 1-px outline, and a
  /// fill held inside a selection (#326).
  func testFillMatchesDesktopFixtureWordForWord() {
    XCTAssertEqual(FloodFillFixture.scenarios.count, 4)
    for scenario in FloodFillFixture.scenarios {
      var buffer = fixtureBuffer()
      let dirty = FloodFill.fill(
        &buffer, x: scenario.seedX, y: scenario.seedY, color: FloodFillFixture.ink,
        tolerance: scenario.tolerance, selection: scenario.selection.map(bits))
      XCTAssertNotNil(dirty, scenario.name)
      XCTAssertEqual(buffer.words, scenario.expected, scenario.name)
    }
  }

  /// The wand's masks (#326) against the desktop's `flood_mask` and
  /// `global_mask`: the connected region, every pixel in range, and
  /// tolerance 0 across a disconnected column.
  func testWandMasksMatchDesktopFixture() {
    XCTAssertEqual(FloodFillFixture.wandScenarios.count, 3)
    let buffer = fixtureBuffer()
    for scenario in FloodFillFixture.wandScenarios {
      let found = buffer.withWords { words in
        scenario.contiguous
          ? FloodFill.mask(
            words: words, width: buffer.width, height: buffer.height,
            x: scenario.seedX, y: scenario.seedY, tolerance: scenario.tolerance)
          : FloodFill.globalMask(
            words: words, width: buffer.width, height: buffer.height,
            x: scenario.seedX, y: scenario.seedY, tolerance: scenario.tolerance)
      }
      XCTAssertEqual(found?.mask, bits(scenario.expected), scenario.name)
    }
  }

  func testSeedOutsideTheSelectionFindsNothing() {
    // The desktop's `if not fillable[y, x]: return None`: a fill or wand
    // whose seed is outside the selection does nothing at all.
    let buffer = fixtureBuffer()
    var leftHalf = [Bool](repeating: false, count: buffer.width * buffer.height)
    for y in 0..<buffer.height { for x in 0..<6 { leftHalf[y * buffer.width + x] = true } }
    let contiguous = buffer.withWords { words in
      FloodFill.mask(
        words: words, width: buffer.width, height: buffer.height, x: 10, y: 0, tolerance: 0,
        selection: leftHalf)
    }
    XCTAssertNil(contiguous)
    let global = buffer.withWords { words in
      FloodFill.globalMask(
        words: words, width: buffer.width, height: buffer.height, x: 10, y: 0, tolerance: 0,
        selection: leftHalf)
    }
    XCTAssertNil(global)
    var copy = buffer
    XCTAssertNil(
      FloodFill.fill(&copy, x: 10, y: 0, color: FloodFillFixture.ink, tolerance: 0, selection: leftHalf))
    XCTAssertEqual(copy.words, buffer.words)
  }

  func testEnclosedRegionNeverLeaksPastAOnePixelOutline() throws {
    // Tolerance 60 admits the white outside (5 from the seed) as well as every
    // grey inside — only the outline keeps them apart, and only 4-connectivity
    // keeps the outline's corners closed.
    let scenario = try XCTUnwrap(FloodFillFixture.scenarios.first { $0.name == "enclosed" })
    var buffer = fixtureBuffer()
    let dirty = try XCTUnwrap(
      FloodFill.fill(
        &buffer, x: scenario.seedX, y: scenario.seedY, color: FloodFillFixture.ink,
        tolerance: scenario.tolerance))
    XCTAssertEqual(dirty, PixelRect(x: 3, y: 3, width: 6, height: 4))
    for y in 0..<buffer.height {
      for x in 0..<buffer.width {
        let inside = (3...8).contains(x) && (3...6).contains(y)
        XCTAssertEqual(
          buffer.word(x: x, y: y) == FloodFillFixture.ink, inside, "pixel (\(x), \(y))")
      }
    }
  }

  func testToleranceIsPerChannelOnPremultipliedWords() {
    // Mirrors _tolerance_mask: the largest channel difference decides, alpha
    // included, and tolerance 0 is exact equality.
    XCTAssertTrue(FloodFill.withinTolerance(0xFF10_2030, of: 0xFF10_2030, tolerance: 0))
    XCTAssertFalse(FloodFill.withinTolerance(0xFF10_2031, of: 0xFF10_2030, tolerance: 0))
    XCTAssertTrue(FloodFill.withinTolerance(0xFF10_2035, of: 0xFF10_2030, tolerance: 5))
    XCTAssertFalse(FloodFill.withinTolerance(0xFF10_2036, of: 0xFF10_2030, tolerance: 5))
    XCTAssertFalse(FloodFill.withinTolerance(0xF010_2030, of: 0xFF10_2030, tolerance: 5))
    XCTAssertTrue(FloodFill.withinTolerance(0xF010_2030, of: 0xFF10_2030, tolerance: 15))
  }

  func testSeedAlreadyInkColourOrOutsideChangesNothing() {
    var buffer = fixtureBuffer()
    XCTAssertNil(FloodFill.fill(&buffer, x: -1, y: 0, color: FloodFillFixture.ink, tolerance: 0))
    XCTAssertNil(FloodFill.fill(&buffer, x: 0, y: 99, color: FloodFillFixture.ink, tolerance: 0))
    // Filling white with white: the desktop returns None before flooding.
    XCTAssertNil(FloodFill.fill(&buffer, x: 0, y: 0, color: 0xFFFF_FFFF, tolerance: 255))
    XCTAssertEqual(buffer.words, FloodFillFixture.input)
  }

  func testBucketFillsTheActiveLayerAsOneUndoStep() throws {
    let store = EditorStore()
    store.newDocument(size: CGSize(width: 32, height: 24))
    let undoManager = UndoManager()
    store.undoManager = undoManager
    let ink = UIColor(red: 1, green: 0, blue: 0, alpha: 1)

    let outcome = store.paintBucket(
      at: CGPoint(x: 10.4, y: 5.9), tolerance: 0, color: ink, opacity: 0.5)
    XCTAssertEqual(outcome, .filled)
    XCTAssertEqual(undoManager.undoActionName, "Paint Bucket")
    let filled = try XCTUnwrap(PixelBuffer(image: try XCTUnwrap(store.activeLayer).image))
    // The whole white canvas is one region; every pixel is the premultiplied
    // half-red the desktop bucket writes for a 50% opacity fill.
    let expected = PixelBuffer.premultipliedWord(r: 255, g: 0, b: 0, a: 128)
    XCTAssertEqual(expected, 0x8080_0000)
    XCTAssertTrue(filled.words.allSatisfy { $0 == expected })

    // Tapping the same spot again with the same ink changes nothing.
    XCTAssertEqual(
      store.paintBucket(at: CGPoint(x: 10, y: 5), tolerance: 0, color: ink, opacity: 0.5),
      .unchanged)
    undoManager.undo()
    let restored = try XCTUnwrap(PixelBuffer(image: try XCTUnwrap(store.activeLayer).image))
    XCTAssertTrue(restored.words.allSatisfy { $0 == 0xFFFF_FFFF })
    XCTAssertFalse(undoManager.canUndo)
  }

  func testBucketRefusesTextLayersAndPointsOffCanvas() throws {
    let store = EditorStore()
    store.newDocument(size: CGSize(width: 32, height: 24))
    XCTAssertEqual(
      store.paintBucket(at: CGPoint(x: 32, y: 0), tolerance: 0, color: .red, opacity: 1),
      .unchanged)
    XCTAssertTrue(store.addTextLayer("T", fontSize: 12, color: .black, at: CGPoint(x: 2, y: 2)))
    XCTAssertEqual(
      store.paintBucket(at: CGPoint(x: 1, y: 1), tolerance: 0, color: .red, opacity: 1),
      .textLayer)
  }
}
