// SPDX-License-Identifier: Apache-2.0
import UIKit
import XCTest

@testable import PhotoslopIPad

/// The rectangle and lasso selections and the feather (#370) against what the
/// desktop produced.
///
/// `SelectionFixture` is generated by `scripts/gen-selection-fixture.py`
/// running `photoslop.npimage.selection_mask` — Qt's aliased odd-even
/// `fillPath` — and `npimage.feathered_weights` over the same shapes, so the
/// masks here are pixel-for-pixel identity with the desktop and the weights
/// are identity to within one level of 255.
@MainActor
final class SelectionParityTests: XCTestCase {
  private let width = SelectionFixture.width
  private let height = SelectionFixture.height

  private func rows(_ mask: SelectionMask) -> [String] {
    (0..<mask.height).map { y in
      String((0..<mask.width).map { mask.contains(x: $0, y: y) ? "#" : "." })
    }
  }

  private func bits(_ rows: [String]) -> [Bool] {
    rows.flatMap { $0.map { $0 == "#" } }
  }

  /// Whole, fractional, reversed, overflowing, centre-tied and sub-pixel
  /// rectangles all select the desktop's pixels.
  func testRectanglesMatchDesktopPixelForPixel() {
    XCTAssertEqual(SelectionFixture.rectScenarios.count, 6)
    for scenario in SelectionFixture.rectScenarios {
      let mask = SelectionMask.rectangle(
        from: scenario.from, to: scenario.to, width: width, height: height)
      XCTAssertEqual(rows(mask), scenario.expected, scenario.name)
      XCTAssertEqual(mask.feather, 0, scenario.name)
    }
  }

  /// Convex, concave, self-crossing (bow tie, star), off-canvas, sub-pixel
  /// and degenerate polygons all fill under the desktop's odd-even rule.
  func testLassoPolygonsMatchDesktopPixelForPixel() {
    XCTAssertEqual(SelectionFixture.lassoScenarios.count, 7)
    for scenario in SelectionFixture.lassoScenarios {
      let mask = SelectionMask.polygon(scenario.points, width: width, height: height)
      XCTAssertEqual(rows(mask), scenario.expected, scenario.name)
    }
    // The star is the odd-even proof: a nonzero fill would take its centre.
    let star = SelectionFixture.lassoScenarios.first { $0.name == "star" }!
    let mask = SelectionMask.polygon(star.points, width: width, height: height)
    XCTAssertFalse(mask.contains(x: 12, y: 10), "the star's centre pentagon is not selected")
    XCTAssertTrue(mask.contains(x: 12, y: 4), "the star's top point is")
  }

  /// Feather weights against the desktop's float ratios, to one level.
  func testFeatherWeightsMatchDesktopWithinOneLevel() {
    XCTAssertEqual(SelectionFixture.featherScenarios.count, 6)
    for scenario in SelectionFixture.featherScenarios {
      let hard = SelectionMask(width: width, height: height, bits: bits(scenario.mask))
      let soft = hard.feathered(by: scenario.feather)
      XCTAssertEqual(soft.feather, scenario.feather, scenario.name)
      XCTAssertEqual(soft.bits, hard.bits, "\(scenario.name): the hard mask is untouched")
      XCTAssertEqual(soft.bounds, hard.bounds, scenario.name)
      XCTAssertEqual(soft.count, hard.count, scenario.name)
      XCTAssertNotEqual(soft.id, hard.id, scenario.name)
      guard let weights = soft.weights else {
        XCTFail("\(scenario.name): no weights")
        continue
      }
      XCTAssertEqual(weights.count, scenario.expected.count, scenario.name)
      var worst = 0
      for i in weights.indices {
        worst = max(worst, abs(Int(weights[i]) - Int(scenario.expected[i])))
      }
      XCTAssertLessThanOrEqual(worst, 1, "\(scenario.name): weights differ by up to \(worst)")
      for i in weights.indices {
        XCTAssertEqual(soft.weight(at: i), weights[i], scenario.name)
      }
    }
  }

  /// A hard selection weighs 255 inside and 0 outside; feathering by 0 (or
  /// less) is a hard edge again.
  func testHardSelectionWeights() {
    let hard = SelectionMask.rectangle(
      from: CGPoint(x: 2, y: 2), to: CGPoint(x: 6, y: 6), width: width, height: height)
    XCTAssertNil(hard.weights)
    XCTAssertEqual(hard.weight(at: 3 * width + 3), 255)
    XCTAssertEqual(hard.weight(at: 0), 0)
    let soft = hard.feathered(by: 8)
    XCTAssertNotNil(soft.weights)
    let hardAgain = soft.feathered(by: 0)
    XCTAssertNil(hardAgain.weights)
    XCTAssertEqual(hardAgain.feather, 0)
    XCTAssertEqual(hardAgain.weight(at: 3 * width + 3), 255)
  }

  /// The feather sits on one selection: combining or inverting starts a new,
  /// hard one, as the desktop's `set_selection` resets `selection_feather`.
  func testFeatherDoesNotSurviveANewSelection() {
    let soft = SelectionMask.rectangle(
      from: CGPoint(x: 2, y: 2), to: CGPoint(x: 6, y: 6), width: width, height: height
    ).feathered(by: 4)
    let other = SelectionMask.rectangle(
      from: CGPoint(x: 4, y: 4), to: CGPoint(x: 9, y: 9), width: width, height: height)
    XCTAssertEqual(soft.united(with: other).feather, 0)
    XCTAssertNil(soft.united(with: other).weights)
    XCTAssertEqual(soft.subtracting(other).feather, 0)
    XCTAssertEqual(soft.inverted().feather, 0)
  }
}
