# SPDX-License-Identifier: Apache-2.0
"""Regenerate the iOS paint-bucket parity fixture from the desktop flood fill.

The Swift port in ``ipados/Photoslop/FloodFill.swift`` (#325) claims identity
with ``photoslop.npimage.flood_fill``, not mere similarity. This script is the
proof: it builds a small synthetic ``QImage``, runs the *desktop* fill over it
for each scenario, and writes the before/after pixels as a Swift source file
that ``FloodFillParityTests`` compares against word for word.

Pixels are written as the ``view_u32`` values — little-endian ``ARGB32``
premultiplied — which is exactly the word a ``PixelBuffer`` exposes on iOS.

Run from the repository root::

    QT_QPA_PLATFORM=offscreen uv run python scripts/gen-flood-fill-fixture.py
"""

from __future__ import annotations

import sys
from pathlib import Path

from PySide6.QtGui import QImage

from photoslop import npimage

OUT = (
    Path(__file__).resolve().parent.parent / "ipados/PhotoslopTests/Fixtures/FloodFillFixture.swift"
)

W, H = 12, 10

# Named premultiplied words. Every scenario shares one canvas so a single
# input array serves all of them.
WHITE = npimage.premultiplied_u32(255, 255, 255, 255)
BLACK = npimage.premultiplied_u32(0, 0, 0, 255)
NEAR_A = npimage.premultiplied_u32(250, 250, 250, 255)  # 5 from white, 10 from NEAR_B
NEAR_B = npimage.premultiplied_u32(240, 240, 240, 255)
FAR = npimage.premultiplied_u32(200, 200, 200, 255)  # 50 from NEAR_A
HALF_RED = npimage.premultiplied_u32(255, 0, 0, 128)  # premultiplies to 0x80800000

# The fill ink: dodger blue at 50% opacity, premultiplied the way the desktop
# bucket does it (round(opacity * 2.55) for the alpha, then r * a // 255).
INK = npimage.premultiplied_u32(30, 144, 255, round(50 * 2.55))


def build_canvas() -> QImage:
    """White canvas, a closed 1-px black box whose interior is banded in
    near-white greys, and a column of half-transparent red down the right."""
    img = QImage(W, H, QImage.Format.Format_ARGB32_Premultiplied)
    arr = npimage.view_u32(img)
    arr[:, :] = WHITE
    arr[2:8, 2:10] = BLACK  # box outline rows 2..7, cols 2..9
    arr[3, 3:9] = NEAR_A
    arr[4, 3:9] = NEAR_B
    arr[5, 3:9] = FAR
    arr[6, 3:9] = NEAR_A
    arr[:, 11] = HALF_RED
    return img


# (name, seed x, seed y, tolerance, what the scenario proves)
SCENARIOS = [
    ("exactOutside", 0, 0, 0, "tolerance 0 fills only the exact-white region outside the box"),
    ("midInside", 3, 3, 20, "tolerance 20 crosses the 10-step band but stops at the 50-step one"),
    (
        "enclosed",
        3,
        3,
        60,
        "tolerance 60 takes the whole interior and never leaks past the 1-px box",
    ),
]


def words(arr) -> str:
    rows = []
    for y in range(H):
        rows.append("      " + ", ".join(f"0x{int(v):08X}" for v in arr[y]) + ",")
    return "\n".join(rows)


def main() -> int:
    base = build_canvas()
    out = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// GENERATED by scripts/gen-flood-fill-fixture.py from the desktop",
        "// photoslop.npimage.flood_fill — do not edit by hand. Regenerate with:",
        "//   QT_QPA_PLATFORM=offscreen uv run python scripts/gen-flood-fill-fixture.py",
        "",
        "/// Desktop-produced expected pixels for the iOS paint bucket (#325).",
        "/// Words are little-endian ARGB32 premultiplied, i.e. `PixelBuffer.words`.",
        "enum FloodFillFixture {",
        f"  static let width = {W}",
        f"  static let height = {H}",
        f"  static let ink: UInt32 = 0x{INK:08X}",
        "",
        "  static let input: [UInt32] = [",
        words(npimage.view_u32(base)),
        "  ]",
        "",
        "  struct Scenario {",
        "    let name: String",
        "    let seedX: Int",
        "    let seedY: Int",
        "    let tolerance: Int",
        "    let expected: [UInt32]",
        "  }",
        "",
        "  static let scenarios: [Scenario] = [",
    ]
    for name, x, y, tol, doc in SCENARIOS:
        img = base.copy()
        dirty = npimage.flood_fill(img, x, y, INK, tol)
        if dirty is None:
            print(f"scenario {name} changed nothing", file=sys.stderr)
            return 1
        out += [
            f"    // {doc}",
            f'    Scenario(name: "{name}", seedX: {x}, seedY: {y}, tolerance: {tol}, expected: [',
            words(npimage.view_u32(img)),
            "    ]),",
        ]
    out += ["  ]", "}", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(out))
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
