# SPDX-License-Identifier: Apache-2.0
"""Regenerate the iOS fill-override parity fixture from the desktop renderer.

Gaussian Blur and Feather are the desktop's two *fill-replacing* effects
(#372): instead of adding a coloured plane beside the layer, they run
``npimage.gaussian_blur`` over the layer's premultiplied RGBA and hand back a
replacement fill. ``AppearanceRenderer.blurRGBA`` claims to be that same
triple box blur, banded the way ``npimage._halo_bands`` bands it — and the
claim only means something if the words match exactly, which is what this
fixture is for.

The blur is deliberately exercised at a radius wide enough that the halo
spans more than one iOS band, so a banding bug cannot hide.

Run from the repository root::

    QT_QPA_PLATFORM=offscreen uv run python scripts/gen-fill-override-fixture.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
from PySide6.QtGui import QColor, QImage, QPainter

from photoslop import npimage

OUT = (
    Path(__file__).resolve().parent.parent
    / "ipados/PhotoslopTests/Fixtures/FillOverrideFixture.swift"
)

W, H = 24, 40  # taller than one iOS band would be at these radii
RADII = (3, 9)
FORMAT = QImage.Format.Format_ARGB32_Premultiplied


def source() -> QImage:
    """A shape with hard edges, partial alpha and colour, so the blur has
    something to smear in every channel rather than only in alpha."""
    img = QImage(W, H, FORMAT)
    img.fill(QColor(0, 0, 0, 0))
    p = QPainter(img)
    p.fillRect(4, 4, 10, 12, QColor(220, 40, 40, 255))
    p.fillRect(10, 14, 11, 18, QColor(30, 90, 210, 160))
    p.fillRect(2, 30, 6, 6, QColor(250, 250, 90, 90))
    p.end()
    return img


def words(img: QImage) -> list[int]:
    return [int(v) for v in npimage.view_u32(img).flatten()]


def feathered(img: QImage, radius: int) -> QImage:
    """`appearance.render`'s feather branch: blur, then keep the *lesser* of
    the blurred and original alpha so the silhouette is only eaten into, never
    grown, with the colour rescaled to the alpha that survives."""
    original_alpha = (npimage.view_u32(img) >> np.uint32(24)) & 0xFF
    blurred = QImage(img)
    npimage.gaussian_blur(blurred, max(1, radius))
    packed = npimage.view_u32(blurred)
    blurred_alpha = (packed >> np.uint32(24)) & 0xFF
    target = np.minimum(blurred_alpha, original_alpha).astype(np.uint32)
    old = blurred_alpha.astype(np.float32)
    scale = target / np.maximum(old, 1)
    red = (((packed >> np.uint32(16)) & 0xFF) * scale).astype(np.uint32)
    green = (((packed >> np.uint32(8)) & 0xFF) * scale).astype(np.uint32)
    blue = ((packed & 0xFF) * scale).astype(np.uint32)
    packed[:] = (target << np.uint32(24)) | (red << np.uint32(16)) | (green << np.uint32(8)) | blue
    return blurred


def rows(values: list[int]) -> list[str]:
    out, line = [], "    "
    for value in values:
        chunk = f"0x{value:08X}, "
        if len(line) + len(chunk) > 96:
            out.append(line.rstrip())
            line = "    "
        line += chunk
    if line.strip():
        out.append(line.rstrip())
    return out


def main() -> None:
    src = source()
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by scripts/gen-fill-override-fixture.py — do not edit.",
        "//",
        "// The desktop's gaussian_blur and feather over premultiplied RGBA, which",
        "// AppearanceRenderer.blurRGBA and the feather branch must reproduce word",
        "// for word. The radii here make the blur halo span more than one iOS",
        "// band, so a banding mistake cannot hide behind a small picture.",
        "",
        "enum FillOverrideFixture {",
        f"  static let width = {W}",
        f"  static let height = {H}",
        "",
        "  static let source: [UInt32] = [",
        *rows(words(src)),
        "  ]",
        "",
        "  struct Case {",
        "    let radius: Int",
        "    let blurred: [UInt32]",
        "    let feathered: [UInt32]",
        "  }",
        "",
        "  static let cases: [Case] = [",
    ]
    for radius in RADII:
        blurred = QImage(src)
        npimage.gaussian_blur(blurred, max(1, radius))
        lines += [
            "    Case(",
            f"      radius: {radius},",
            "      blurred: [",
            *rows(words(blurred)),
            "      ],",
            "      feathered: [",
            *rows(words(feathered(src, radius))),
            "      ]",
            "    ),",
        ]
    lines += ["  ]", "}", ""]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(Path.cwd())} ({W}x{H}, radii {RADII})")


if __name__ == "__main__":
    main()
