# SPDX-License-Identifier: Apache-2.0
"""Regenerate the iOS dither parity fixture from the desktop engine.

``ipados/Photoslop/Dither.swift`` (#385) claims to be a port of
``photoslop.dither`` — the same error-diffusion kernels scanned the same
serpentine way, the same Bayer doubling recurrence, the same beam model. This
script is the proof: it runs the *desktop* engine over a synthetic plane and
writes what came out as a Swift source file that ``DitherParityTests`` demands
back.

Everything is float64 on both sides. That is not incidental: a dither turns a
rounding difference into a different pixel being lit, so a float32 plane here
against a `Double` there would disagree visibly rather than subtly.

Run from the repository root::

    QT_QPA_PLATFORM=offscreen uv run python scripts/gen-dither-fixture.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

from photoslop import dither

OUT = Path(__file__).resolve().parent.parent / "ipados/PhotoslopTests/Fixtures/DitherFixture.swift"

W, H = 23, 17  # deliberately not multiples of any Bayer size or kernel reach


def plane() -> np.ndarray:
    """A ramp with a bright disc and a dark bar: smooth gradient for the error
    kernels to track, hard edges for them to ring against, and flat extremes at
    both ends so clipping shows up."""
    y, x = np.mgrid[0:H, 0:W].astype(np.float64)
    out = x / (W - 1)
    disc = ((x - 6) ** 2 + (y - 5) ** 2) < 9
    out[disc] = 0.95
    out[12:15, 3:18] = 0.05
    return np.clip(out, 0.0, 1.0)


def literals(values: np.ndarray) -> list[str]:
    out, line = [], "    "
    for value in values.flatten():
        chunk = f"{float(value):.17g}, "
        if len(line) + len(chunk) > 96:
            out.append(line.rstrip())
            line = "    "
        line += chunk
    if line.strip():
        out.append(line.rstrip())
    return out


def main() -> None:
    source = plane()
    lines = [
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by scripts/gen-dither-fixture.py — do not edit.",
        "//",
        "// What photoslop.dither produced, which Dither.swift must reproduce.",
        "// float64 throughout: a dither turns a rounding difference into a",
        "// different pixel being lit, so this is not a tolerance comparison.",
        "",
        "enum DitherFixture {",
        f"  static let width = {W}",
        f"  static let height = {H}",
        "",
        "  static let source: [Double] = [",
        *literals(source),
        "  ]",
        "",
        "  struct Case {",
        "    let name: String",
        "    let levels: Int",
        "    let expected: [Double]",
        "  }",
        "",
        "  static let errorDiffusion: [Case] = [",
    ]
    for kernel in sorted(dither.ERROR_KERNELS):
        for levels in (2, 4):
            got = dither.error_diffuse(source, kernel, levels)
            lines += [
                "    Case(",
                f'      name: "{kernel}",',
                f"      levels: {levels},",
                "      expected: [",
                *literals(np.asarray(got, dtype=np.float64)),
                "      ]",
                "    ),",
            ]
    lines += ["  ]", "", "  static let ordered: [Case] = ["]
    for size in (2, 4, 8):
        for levels in (2, 3):
            got = dither.ordered_dither(source, size, levels)
            lines += [
                "    Case(",
                f'      name: "bayer-{size}",',
                f"      levels: {levels},",
                "      expected: [",
                *literals(np.asarray(got, dtype=np.float64)),
                "      ]",
                "    ),",
            ]
    lines += [
        "  ]",
        "",
        "  struct BeamCase {",
        "    let pitch: Int",
        "    let amplitude: Double",
        "    let expected: [Double]",
        "  }",
        "",
        "  static let beams: [BeamCase] = [",
    ]
    for pitch, amplitude in ((6, 0.0), (6, 1.5), (11, 3.25)):
        got = dither.beam_mask(source, pitch, amplitude)
        lines += [
            "    BeamCase(",
            f"      pitch: {pitch},",
            f"      amplitude: {amplitude!r},",
            "      expected: [",
            *literals(np.asarray(got, dtype=np.float64)),
            "      ]",
            "    ),",
        ]
    lines += [
        "  ]",
        "",
        "  static let bayer4: [Double] = [",
        *literals(dither.bayer_matrix(4)),
        "  ]",
        "}",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT.relative_to(Path.cwd())} ({W}x{H})")


if __name__ == "__main__":
    main()
